<?php

$finder = (new PhpCsFixer\Finder())
	->in([
		__DIR__ . DIRECTORY_SEPARATOR . 'src',
		__DIR__ . DIRECTORY_SEPARATOR . 'public',
		__DIR__ . DIRECTORY_SEPARATOR . 'config',
		__DIR__ . DIRECTORY_SEPARATOR . 'tests',
	])
	->notPath([
		'\.\/config\/reference\.php',
	]);

return (new PhpCsFixer\Config())
	->setRiskyAllowed(true)
	->setRules([
		'@PSR12' => true,
		'elseif' => true,
		'encoding' => true,
		'no_multiline_whitespace_around_double_arrow' => true,
		'no_whitespace_before_comma_in_array' => true,
		'normalize_index_brace' => true,
		'trim_array_spaces' => true,
		'whitespace_after_comma_in_array' => [
			'ensure_single_space' => true,
		],
		'braces_position' => [
			'allow_single_line_anonymous_functions' => false,
			'allow_single_line_empty_anonymous_classes' => false,
			'anonymous_classes_opening_brace' => 'same_line',
			'anonymous_functions_opening_brace' => 'same_line',
			'classes_opening_brace' => 'same_line',
			'control_structures_opening_brace' => 'same_line',
			'functions_opening_brace' => 'same_line',
		],
		'return_to_yield_from' => true,
		'class_reference_name_casing' => true,
		'lowercase_keywords' => true,
		'lowercase_static_reference' => true,
		'magic_constant_casing' => true,
		'magic_method_casing' => true,
		'native_function_casing' => true,
		'native_type_declaration_casing' => true,
		'no_multiple_statements_per_line' => true,
		'no_trailing_comma_in_singleline' => true,
		'numeric_literal_separator' => [
			'override_existing' => true,
			'strategy' => 'use_separator',
		],
		'octal_notation' => true,
		'single_line_empty_body' => false,
		'constant_case' => [
			'case' => 'lower',
		],
		'integer_literal_case' => true,
		'cast_spaces' => [
			'space' => 'single',
		],
		'lowercase_cast' => true,
		'no_short_bool_cast' => true,
		'no_unset_cast' => true,
		'short_scalar_cast' => true,
		'class_attributes_separation' => [
			'elements' => [
				'const' => 'one',
				'method' => 'one',
				'property' => 'one',
				'trait_import' => 'none',
				'case' => 'one',
			],
		],
		'class_definition' => [
			'inline_constructor_arguments' => false,
			'multi_line_extends_each_single_line' => true,
			'single_item_single_line' => true,
			'single_line' => false,
			'space_before_parenthesis' => true,
		],
		'no_blank_lines_after_class_opening' => true,
		'no_null_property_initialization' => false,
		'ordered_class_elements' => [
			'case_sensitive' => true,
			'order' => [
				'use_trait',
				'case',
				'constant_public',
				'constant_protected',
				'constant_private',
				'property_public',
				'property_protected',
				'property_private',
				'construct',
				'destruct',
				'magic',
				'phpunit',
				'method_public',
				'method_protected',
				'method_private',
			],
		],
		'ordered_interfaces' => [
			'case_sensitive' => true,
			'order' => 'alpha',
			'direction' => 'ascend',
		],
		'self_static_accessor' => true,
		'single_class_element_per_statement' => [
			'elements' => ['const', 'property'],
		],
		'visibility_required' => [
			'elements' => ['const', 'property', 'method'],
		],
		'header_comment' => [
			'comment_type' => 'PHPDoc',
			'header' => '@author Nikita Prokopenko <radynje@gmail.com>',
			'location' => 'after_open',
			'separate' => 'both',
		],
		'multiline_comment_opening_closing' => true,
		'no_empty_comment' => true,
		'no_trailing_whitespace_in_comment' => true,
		'single_line_comment_spacing' => true,
		'single_line_comment_style' => [
			'comment_types' => ['asterisk', 'hash'],
		],
		'control_structure_braces' => true,
		'control_structure_continuation_position' => [
			'position' => 'same_line',
		],
		'empty_loop_body' => [
			'style' => 'braces',
		],
		'empty_loop_condition' => [
			'style' => 'while',
		],
		'include' => true,
		'no_alternative_syntax' => [
			'fix_non_monolithic_code' => false,
		],
		'no_superfluous_elseif' => true,
		'no_unneeded_braces' => true,
		'no_unneeded_control_parentheses' => [
			'statements' => [
				'break',
				'clone',
				'continue',
				'echo_print',
				'negative_instanceof',
				'others',
				'return',
				'switch_case',
				'yield',
				'yield_from',
			],
		],
		'no_useless_else' => true,
		'simplified_if_return' => true,
		'switch_case_semicolon_to_colon' => true,
		'switch_case_space' => true,
		'trailing_comma_in_multiline' => [
			'after_heredoc' => true,
			'elements' => ['arguments', 'arrays', 'match', 'parameters'],
		],
		'yoda_style' => [
			'equal' => false,
			'identical' => false,
			'less_and_greater' => false,
			'always_move_variable' => false,
		],
		'function_declaration' => [
			'closure_fn_spacing' => 'one',
			'closure_function_spacing' => 'one',
			'trailing_comma_single_line' => false,
		],
		'lambda_not_used_import' => true,
		'method_argument_space' => [
			'keep_multiple_spaces_after_comma' => false,
			'on_multiline' => 'ensure_fully_multiline',
			'attribute_placement' => 'standalone',
			'after_heredoc' => true,
		],
		'no_spaces_after_function_name' => true,
		'nullable_type_declaration_for_default_null_value' => true,
		'return_type_declaration' => [
			'space_before' => 'none',
		],
		'single_line_throw' => false,
		'fully_qualified_strict_types' => [
			'import_symbols' => true,
			'leading_backslash_in_global_namespace' => false,
			'phpdoc_tags' => [
				'param',
				'phpstan-param',
				'phpstan-property',
				'phpstan-property-read',
				'phpstan-property-write',
				'phpstan-return',
				'phpstan-var',
				'property',
				'property-read',
				'property-write',
				'psalm-param',
				'psalm-property',
				'psalm-property-read',
				'psalm-property-write',
				'psalm-return',
				'psalm-var',
				'return',
				'see',
				'throws',
				'var',
			],
		],
		'global_namespace_import' => [
			'import_classes' => true,
			'import_constants' => false,
			'import_functions' => false,
		],
		'group_import' => false,
		'no_leading_import_slash' => true,
		'no_unneeded_import_alias' => true,
		'no_unused_imports' => true,
		'ordered_imports' => [
			'case_sensitive' => true,
			'imports_order' => ['const', 'function', 'class'],
			'sort_algorithm' => 'alpha',
		],
		'single_import_per_statement' => [
			'group_to_single_imports' => true,
		],
		'single_line_after_imports' => true,
		'combine_consecutive_issets' => true,
		'combine_consecutive_unsets' => true,
		'declare_equal_normalize' => [
			'space' => 'single',
		],
		'declare_parentheses' => true,
		'explicit_indirect_variable' => true,
		'nullable_type_declaration' => [
			'syntax' => 'question_mark',
		],
		'single_space_around_construct' => [
			'constructs_contain_a_single_space' => ['yield_from'],
			'constructs_followed_by_a_single_space' => [
				'abstract',
				'as',
				'attribute',
				'break',
				'case',
				'catch',
				'class',
				'clone',
				'comment',
				'const',
				'const_import',
				'continue',
				'do',
				'echo',
				'else',
				'elseif',
				'enum',
				'extends',
				'final',
				'finally',
				'for',
				'foreach',
				'function',
				'function_import',
				'global',
				'goto',
				'if',
				'implements',
				'include',
				'include_once',
				'instanceof',
				'insteadof',
				'interface',
				'match',
				'named_argument',
				'namespace',
				'new',
				'open_tag_with_echo',
				'php_doc',
				'php_open',
				'print',
				'private',
				'protected',
				'public',
				'readonly',
				'require',
				'require_once',
				'return',
				'static',
				'switch',
				'throw',
				'trait',
				'try',
				'type_colon',
				'use',
				'use_lambda',
				'use_trait',
				'var',
				'while',
				'yield',
				'yield_from',
			],
			'constructs_preceded_by_a_single_space' => ['as', 'use_lambda'],
		],
		'list_syntax' => [
			'syntax' => 'short',
		],
		'blank_line_after_namespace' => true,
		'blank_lines_before_namespace' => [
			'max_line_breaks' => 2,
			'min_line_breaks' => 2,
		],
		'clean_namespace' => true,
		'no_leading_namespace_whitespace' => true,
		'assign_null_coalescing_to_coalesce_equal' => true,
		'binary_operator_spaces' => [
			'default' => 'single_space',
			'operators' => [],
		],
		'concat_space' => [
			'spacing' => 'one',
		],
		'new_with_parentheses' => [
			'anonymous_class' => true,
			'named_class' => true,
		],
		'no_space_around_double_colon' => true,
		'no_useless_nullsafe_operator' => true,
		'not_operator_with_space' => false,
		'not_operator_with_successor_space' => false,
		'object_operator_without_whitespace' => true,
		'operator_linebreak' => [
			'only_booleans' => false,
			'position' => 'beginning',
		],
		'standardize_increment' => true,
		'standardize_not_equals' => true,
		'ternary_operator_spaces' => true,
		'ternary_to_null_coalescing' => true,
		'unary_operator_spaces' => true,
		'blank_line_after_opening_tag' => true,
		'echo_tag_syntax' => [
			'format' => 'long',
			'long_function' => 'echo',
			'shorten_simple_statements_only' => false,
		],
		'full_opening_tag' => true,
		'linebreak_after_opening_tag' => false,
		'no_closing_tag' => true,
		'align_multiline_comment' => [
			'comment_type' => 'phpdocs_only',
		],
		'general_phpdoc_tag_rename' => [
			'case_sensitive' => false,
			'fix_annotation' => true,
			'fix_inline' => true,
			'replacements' => [
				'inheritDocs' => 'inheritDoc',
			],
		],
		'no_blank_lines_after_phpdoc' => true,
		'no_empty_phpdoc' => true,
		'phpdoc_add_missing_param_annotation' => [
			'only_untyped' => true,
		],
		'phpdoc_align' => [
			'align' => 'left',
			'spacing' => 1,
			'tags' => [
				'param',
				'property',
				'property-read',
				'property-write',
				'phpstan-param',
				'phpstan-property',
				'phpstan-property-read',
				'phpstan-property-write',
				'phpstan-assert',
				'phpstan-assert-if-true',
				'phpstan-assert-if-false',
				'psalm-param',
				'psalm-param-out',
				'psalm-property',
				'psalm-property-read',
				'psalm-property-write',
				'psalm-assert',
				'psalm-assert-if-true',
				'psalm-assert-if-false',
				'method',
				'phpstan-method',
				'psalm-method',
				'return',
				'throws',
				'type',
				'var',
				'extends',
				'implements',
				'template',
				'template-extends',
				'todo',
				'example',
				'deprecated',
				'since',
				'package',
				'subpackage',
			],
		],
		'phpdoc_annotation_without_dot' => false,
		'phpdoc_indent' => true,
		'phpdoc_inline_tag_normalizer' => true,
		'phpdoc_line_span' => [
			'const' => 'multi',
			'method' => 'multi',
			'property' => 'multi',
		],
		'phpdoc_no_access' => true,
		'phpdoc_no_empty_return' => false,
		'phpdoc_no_useless_inheritdoc' => true,
		'phpdoc_order' => [
			'order' => [
				'inheritDoc',
				'deprecated',
				'todo',
				'package',
				'subpackage',
				'since',
				'see',
				'link',
				'param',
				'return',
				'throws',
			],
		],
		'phpdoc_param_order' => false,
		'phpdoc_return_self_reference' => [
			'replacements' => [
				'this' => 'static',
				'@this' => 'static',
				'$self' => 'self',
				'@self' => 'self',
				'$static' => 'static',
				'@static' => 'static',
			],
		],
		'phpdoc_scalar' => [
			'types' => [
				'boolean',
				'callback',
				'double',
				'integer',
				'real',
				'str',
			],
		],
		'phpdoc_single_line_var_spacing' => true,
		'phpdoc_tag_casing' => [
			'tags' => ['inheritDoc'],
		],
		'phpdoc_to_comment' => [
			'allow_before_return_statement' => false,
			'ignored_tags' => [],
		],
		'phpdoc_trim_consecutive_blank_line_separation' => true,
		'phpdoc_trim' => true,
		'phpdoc_types' => [
			'groups' => ['alias', 'meta', 'simple'],
		],
		'phpdoc_types_order' => [
			'case_sensitive' => true,
			'null_adjustment' => 'always_last',
			'sort_algorithm' => 'alpha',
		],
		'phpdoc_var_annotation_correct_order' => true,
		'phpdoc_var_without_name' => true,
		'no_useless_return' => true,
		'return_assignment' => true,
		'simplified_null_return' => true,
		'multiline_whitespace_before_semicolons' => [
			'strategy' => 'no_multi_line',
		],
		'no_empty_statement' => true,
		'no_singleline_whitespace_before_semicolons' => true,
		'semicolon_after_instruction' => true,
		'space_after_semicolon' => [
			'remove_in_empty_for_expressions' => true,
		],
		'declare_strict_types' => true,
		'explicit_string_variable' => true,
		'heredoc_closing_marker' => [
			'closing_marker' => 'EOD',
			'explicit_heredoc_style' => false,
			'reserved_closing_markers' => ['SQL', 'MD'],
		],
	])
	->setIndent(chr(9))
	->setLineEnding(chr(10))
	->setFinder($finder);
